name: CI for Django + Vue + Playwright

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r main_backend/requirements.txt

      - name: Run Django Tests
        run: |
          cd main_backend
          python manage.py test

  
